### PR TITLE
Course pagination

### LINKED ISSUE #97: admin: course pagination
right now course's pagination is broken

### PR DESCRIPTION
**Pull request by artificiala**
I want to resolve #97 

Note:
There is a logical error in paginate filter, please review this file. 
```
pkg/view/template.go
```

### CODE REVIEW

File: pkg/app/admin.go [hunk 1]
```diff
@@ -6,6 +6,8 @@ import (
 	"net/http"
 	"strconv"
```
Comment (acoshift) [inline pkg/app/admin.go]: ลบบรรทัดเปล่าให้หน่อย
